### ISSUE TITLE
BloodTestresults Web Screen

### ISSUE THREAD

**Issue by liamehinc** [okkam1/BLT#1]
BloodTestResults.aspx
- remove LabID
- lab should be data driven (drop down)?
- Flag should be yes or no (checkbox/radio button)
- perhaps add notes on why flagged?

**Comment by ccloes** [comment]
@liamehinc @okkam1 ... should I simply grab the oldest and start working?  Or are there others that you want done first?

**Comment by liamehinc** [comment]
DONE - remove LabID
DONE - lab should be data driven (drop down)?
DONE - Flag should be yes or no (checkbox/radio button) -> integer for number of days in the future (from sample date) to do the follow up
DONE perhaps add notes on why flagged?

**Comment by liamehinc** [comment]
There are 4 that are tagged active, those are the highest priority, I'm working on the  Marco is heading up the other 3, so I'll let him speak to their status and if you can help on them or not.

For now, I think it would be helpful if you worked on any of the following: Blood Test Results Web Screen - source of sample #68Onboard Client for Lead Research Study - ethnicity drop down #60UI - Blood Test Results - child status should be drop down #42UI - Blood Test Results test type should be dropdown list#38UI - BloodtestResulsts.aspx - SampleType should be dropdown #10   

Date: Sun, 8 Mar 2015 19:45:45 -0700
