### ISSUE TITLE
UIDB - Add parent/guardian

### ISSUE THREAD

**Issue by spiet002** [okkam1/BLT#101]
Need the ability to add parent or guardian information (associate with another person).

**Comment by liamehinc** [comment]
Can add relationship types via the database using the usp_InsertPersontoPerson stored procedure with the following parameters:

DECLARE @return_value int

EXEC    @return_value = [dbo].[usp_InsertPersontoPerson]
        @Person1ID = 4282,
        @Person2ID = 4346,
        @RelationshipType = 6,
        @isGuardian = 1,
        @isPrimaryContact = 1

SELECT  'Return Value' = @return_value

GO

relationshipType is how P1 relates to P2
isGuardian is 1 if P1 is P2's guardian
isPrimaryContact is 1 if P1 is P2's primaryContact

**Comment by liamehinc** [comment]
can get a list of relationship types with the following stored procedure:

[usp_SlRelationShipTypes]

**Comment by liamehinc** [comment]
need to track parents/guardians associated to client as per 20150325 meeting with LCCHP

**Comment by liamehinc** [comment]
Lynn is Reviewing this to determine if current implementation of client to family meets these requirements

**Comment by liamehinc** [comment]
Consensus during 6/24 meeting was that contact information in current implementatoin is sufficient. most contact information is available in current paper documentation. This may be added later as an enhancement
