### ISSUE TITLE
Add Family - Moved?

### ISSUE THREAD

**Issue by spiet002** [okkam1/BLT#105]
Track historic houses (moved)

**Comment by liamehinc** [comment]
Clarify with if they really want family or if person is sufficient. Possibly track by relating family to property via person. Time may vary depending on final decision and requirements

**Comment by liamehinc** [comment]
Based on 20150325 meeting with LCCHP - need to track person's historic association with a house. Meh to include option to specify move in and move out dates. handled via the persontopropertyTable and usp_InsertPersonToProperty
