### ISSUE TITLE
UI - Marco - Point 8080 website to Dev

### ISSUE THREAD

**Issue by liamehinc** [okkam1/BLT#11]

**Comment by okkam1** [comment]
was working, but had to point back to pub b/c of an issue preventing scaffolding:

Error   7   The table 'LCCHPDev.dbo.LCCHPAttachments' is referenced by a relationship, but cannot be found. C:\Users\Administrator\Documents\Visual Studio 2012\WebSites\WebSite1\App_Code\Model.edmx   0   0   WebSite1(1)

**Comment by okkam1** [comment]
fixed via working sessions with Liam and Marco
