### ISSUE TITLE
Add a New Family Page --Exception Caught

### ISSUE THREAD

**Issue by liamehinc** [okkam1/BLT#113]
![image](https://cloud.githubusercontent.com/assets/1000622/6701513/a4230256-ccd2-11e4-8a7c-64cbf846f985.png)

**Comment by okkam1** [comment]
Dev issue fixed.  prd needs the newest version of the usp:

error   {"@Address_Line1 is not a parameter for procedure usp_InsertNewFamilyWebScreen."}   System.Exception {System.Data.SqlClient.SqlException}

**Comment by liamehinc** [comment]
updated usp_AddProperty, usp_AddFamily, usp_AddNewFamilyWebScreen stored procedures and the Family and property tables in public. Add family now works in both prod and dev

**Comment by spiet002** [comment]
Verified on 3/22/15
