### ISSUE TITLE
Extend DB to support and differentiate non-client people

### ISSUE THREAD

**Issue by liamehinc** [okkam1/BLT#126]
Add isClient flag to person table and pass issue to Marco for UI work

**Comment by liamehinc** [comment]
duplicate of #124

**Comment by liamehinc** [comment]
this is specific to isClient not nursing or pregnant

**Comment by liamehinc** [comment]
usp_AddNewClientWEbScreen now accepts @is_Client parameter = 1 if the person is a client in the study

**Comment by okkam1** [comment]
I will add this check to all the direct sql calls as well as to the reports.  but we'll also need to update the stored procedures.

**Comment by liamehinc** [comment]
stored procedures where updated in early april
