### ISSUE TITLE
DB - Edit screen - AddClient

### ISSUE THREAD

**Issue by liamehinc** [okkam1/BLT#128]
create stored procedure for edit screen for addClient information

**Comment by liamehinc** [comment]
@okkam1 the update procedure is ready for EditClientInfo.aspx:

USE [LCCHPDev]
GO

DECLARE @return_value int

EXEC    @return_value = [dbo].[usp_upNewClientWebScreen]
        @Family_ID = 2449,
        @Person_ID = 4390,
        @New_FirstName = NULL,
        @New_MiddleName = NULL,
        @New_LastName = NULL,
        @New_BirthDate = NULL,
        @New_Gender = NULL,
        @New_StatusID = NULL,
        @New_ForeignTravel = NULL,
        @New_OutofSite = NULL,
        @New_EatsForeignFood = NULL,
        @New_PatientID = NULL,
        @New_RetestDate = NULL,
        @New_Moved = NULL,
        @New_MovedDate = NULL,
        @New_isClosed = NULL,
        @New_isResolved = NULL,
        @New_GuardianID = NULL,
        @New_PersonCode = NULL,
        @New_isSmoker = NULL,
        @New_isClient = NULL,
        @New_isNursing = NULL,
        @New_isPregnant = NULL,
        @New_EthnicityID = 3,
        @New_LanguageID = NULL,
        @New_PrimaryLanguage = NULL,
        @New_HobbyID = NULL,
        @New_OccupationID = NULL,
        @New_Occupation_StartDate = NULL,
        @New_Occupation_EndDate = NULL,
        @DEBUG = NULL

SELECT  'Return Value' = @return_value

GO

**Comment by liamehinc** [comment]
@okkam1 
The update screen only provides functionality to add to the following:
persontolanguage
persontoethnicity
persontofamily
perosntohobby
persontooccupation (can also update start and end dates for existing relationships)

In order to delete or update existing relationships from the above, the advanced data management needs to be used.

**Comment by okkam1** [comment]
does that mean if they want to add a hobby to a person, they have to use the advanced DM feature?

**Comment by liamehinc** [comment]
the above structure allows for adding new hobby, family, ethnicity, language, and occupation associations to a person via the edit screen. It does not support editing or deleting those associations. If there is a desire to support that through the edit screen, we can add that functionality. 

For now, deleting and editing existing associations can be done through advanced data management.

If you have more questions, we can go over them during monday's meeting/working session.

**Comment by liamehinc** [comment]
RENAMED Stored procedure:  usp_upClientWebScreen

USE [LCCHPDev]
GO

DECLARE @return_value int

EXEC    @return_value = [dbo].[usp_upClientWebScreen]
        @Family_ID = NULL,
        @Person_ID = NULL,
        @New_FirstName = NULL,
        @New_MiddleName = NULL,
        @New_LastName = NULL,
        @New_BirthDate = NULL,
        @New_Gender = NULL,
        @New_StatusID = NULL,
        @New_ForeignTravel = NULL,
        @New_OutofSite = NULL,
        @New_EatsForeignFood = NULL,
        @New_PatientID = NULL,
        @New_RetestDate = NULL,
        @New_Moved = NULL,
        @New_MovedDate = NULL,
        @New_isClosed = NULL,
        @New_isResolved = NULL,
        @New_GuardianID = NULL,
        @New_PersonCode = NULL,
        @New_isSmoker = NULL,
        @New_isClient = NULL,
        @New_isNursing = NULL,
        @New_isPregnant = NULL,
        @New_EthnicityID = NULL,
        @New_LanguageID = NULL,
        @New_PrimaryLanguage = NULL,
        @New_HobbyID = NULL,
        @New_OccupationID = NULL,
        @New_Occupation_StartDate = NULL,
        @New_Occupation_EndDate = NULL,
        @DEBUG = NULL

SELECT  'Return Value' = @return_value

GO
