### ISSUE TITLE
DB - select for Edit screen - AddClient

### ISSUE THREAD

**Issue by liamehinc** [okkam1/BLT#139]
create stored procedure to select data to populate AddClient edit screen with information

**Comment by okkam1** [comment]
FWIW, this is lower priority than perhaps for other screens because I have a working select statement that I am already coding to.

**Comment by liamehinc** [comment]
USE [LCCHPDev]
GO

DECLARE @return_value int

EXEC    @return_value = [dbo].[usp_SlEditClientInfoWebScreenInformation]
        @PersonID = 2,
        @DEBUG = 1

SELECT  'Return Value' = @return_value

GO

**Comment by liamehinc** [comment]
application code can be updated to point to stored procedure:  usp_SlEditClientIfnoWebScreenInformation
