### ISSUE TITLE
DB: update usp_upFamilyWebScreen

### ISSUE THREAD

**Issue by okkam1** [okkam1/BLT#148]
Are we not adding the output fields like in the Add sprocs?  usp_upFamilyWebScreen does not have output params

//command.Parameters.Add("@Family_ID", SqlDbType.Int).Direction = ParameterDirection.Output;  //usp returns ID upon completion

```
        //command.Parameters.Add("@ReturnValue", SqlDbType.Int).Direction = ParameterDirection.ReturnValue;
```

**Comment by liamehinc** [comment]
it's definitely providing a return value, the return value is 0 for success and non-zero for failure. I'm not adding anything new, just updating existing information: 
![image](https://cloud.githubusercontent.com/assets/1000622/7076082/5c2cc732-deb3-11e4-9ed9-e57fb4f5eda7.png)

lets investigate this monday night

**Comment by okkam1** [comment]
you're right; sorry for the confusion.  closing.
