### ISSUE TITLE
DB: possible deadlock is usp_InsertNewFamilyWebScreen?

### ISSUE THREAD

**Issue by okkam1** [okkam1/BLT#160]
When adding a family (using values from attached screenshot) to the add family screen, the first time hangs and the second time returns this error:
-       error   {"Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding."}  System.Exception {System.Data.SqlClient.SqlException}

googling the error suggests that this could possibly be a deadlock.  The Dev DB does not have this problem; perhaps a db promotion will resolve the issue.  But, it may only delay the issue if there is a problem with the sproc.

![screenshot](https://cloud.githubusercontent.com/assets/1072639/7440174/20ed7be2-f058-11e4-9ab4-f3d325bea170.png)

**Comment by liamehinc** [comment]
turns out there was too much overhead in the duplicate checking code. I've simplified the search for duplicates and improved the query performance so this timeout isn't happening.
