### ISSUE TITLE
Fail to add person: ADdClient.aspx

### ISSUE THREAD

**Issue by liamehinc** [okkam1/BLT#165]
![image](https://cloud.githubusercontent.com/assets/1000622/7717313/cab163d6-fe4b-11e4-8060-d24d0e1f7174.png)

I specified the aaaaaFamily and also the 2825 --- 1459 E. Glacier Trail family

both failed to convert parameter value form string to Int32. I'm not seeing anything hit the db. I'm not sure if it's in the web portion or the db, let's try to troubleshoot in the near future.

**Comment by okkam1** [comment]
Fixed.  This bug was introduced accidentally when adding the enhancement to auto select a family in the drop down after a new family is created via AddFamily.  This bug has been fixed in both dev and prod.
