### ISSUE TITLE
Questionnaire.aspx - add new questionnaire fails - ERROR: Input string was not in a correct format

### ISSUE THREAD

**Issue by liamehinc** [okkam1/BLT#166]
Nothing makes it to the database. i suspect it is related to the yes/no questions submitting a blank string instead of null

![image](https://cloud.githubusercontent.com/assets/1000622/7791919/3f98fa30-0255-11e5-8857-cfc896463136.png)

the problem went away when i completed the yes/no for all the fields

**Comment by liamehinc** [comment]
@okkam1 i updated the code for questionnaire.aspx.cs to account for nothing being passed in for the radio button values. I saved the original questionnaire.aspx.cs to D:\questionnaire.aspx.cs

I made the following updates to any rbl datatype value:
ORIGINAL: command.Parameters.Add("@PaintPeeling", SqlDbType.Bit).Value = Convert.ToByte(rblPaintPeeling.SelectedValue);

UPDATED:
if (rblPaintPeeling.SelectedValue != "") 
                command.Parameters.Add("@PaintPeeling", SqlDbType.Bit).Value = Convert.ToByte(rblPaintPeeling.SelectedValue);

i did not commit this code as i didn't want to create any more problems for you in case i missed something.

**Comment by okkam1** [comment]
this fix is perfectly valid.  I have merged this codeline into the develop branch
