### ISSUE TITLE
UI - EditFamily - In and out pets always comes up as No 1st time

### ISSUE THREAD

**Issue by liamehinc** [okkam1/BLT#169]
http://54.69.86.226:8080/EditFamily.aspx
Pets in and out doesn't populate properly on the first load.

i.e. the Winchester Family has in and out pets set to 1 in the db
when i choose to edit the winchester family, pets in and out comes up as no (1 = yes):

![image](https://cloud.githubusercontent.com/assets/1000622/8132724/3e9c0814-10d0-11e5-9922-5d6ad1947e5e.png)

**Comment by okkam1** [comment]
wow, good catch.  It's fixed...
