### ISSUE TITLE
Breadcrumbs not showing up on ClientFollowUp report

### ISSUE THREAD

**Issue by liamehinc** [okkam1/BLT#184]
ClientFollowup.aspx
ListOfClientsbyCreatedDate.aspx
ListOfClientsbyModifiedDate.aspx

http://localhost:8080/ReportPages/ClientFollowUp.aspx

![image](https://cloud.githubusercontent.com/assets/1000622/8734943/eb23af70-2bb9-11e5-8165-fbf5536392eb.png)

**Comment by okkam1** [comment]
fixed
