### ISSUE TITLE
EditClientInfo.aspx - bug with ethnicity field

### ISSUE THREAD

**Issue by liamehinc** [okkam1/BLT#189]
when i try to submit the updates to a client, i receive error that a new ethnicity must be selected. when i change the ethnicity, i receive the same error.

This happens in both dev and public

![image](https://cloud.githubusercontent.com/assets/1000622/8763501/b3aba096-2d4b-11e5-99c5-c7d8c25ebf7d.png)

**Comment by okkam1** [comment]
fixed. there was a proposal for a user control to have a better UI experience; but putting that everywhere would be outside the scope of this project.
