### ISSUE TITLE
DB - NULL Birthdates

### ISSUE THREAD

**Issue by liamehinc** [okkam1/BLT#19]
how to deal with historic birthdates that are null.
   There are currently 2 
          Select \* from Person where PersonCode in ('10576','10577')

Going forward require a birthdate field is required (NOT NULL)

**Comment by liamehinc** [comment]
These records appear to be completely blank in the original dataset, and are likely candidates for removal

**Comment by okkam1** [comment]
left open as notes for migration

**Comment by liamehinc** [comment]
details are in email from Cornelia on 2/12/2015

**Comment by liamehinc** [comment]
completed, null birthdates where set to birthdates specified by Cornelia in 2/12/2015 email
