### ISSUE TITLE
Summary report - clients = 4; new clients = 6

### ISSUE THREAD

**Issue by liamehinc** [okkam1/BLT#207]
how is this possible?

![image](https://cloud.githubusercontent.com/assets/1000622/8913404/6819dc6e-3445-11e5-87ab-ee9411b1b937.png)

**Comment by okkam1** [comment]
FWIW, i checked the report and it is using the correct params from the sProc:

![image](https://cloud.githubusercontent.com/assets/1072639/8918419/b2c4586c-346c-11e5-9beb-674d5f8d6325.png)

**Comment by liamehinc** [comment]
The logic is different for selecting clients and selecting newclients:

clients are any people that have a bloodtest or questionnaire entry during the specified time period
new clients are any people that were created during the specified time period, even if they do not have a blood test or questionnaire entered.

resolved by re-defining as follows:

a.  Clients are any people with a blood test or questionnaire entry during the specified time period and isClient attribute set to yes; 
b.  new clients are people created in the specified time period with the isClient attribute set to yes and also have either a blood test entry or questionnaire entry during the specified time period
