### ISSUE TITLE
UI - DB - Data purity

### ISSUE THREAD

**Issue by liamehinc** [okkam1/BLT#22]
print out all screens and ask LCCHP which fields should have default values if any, realizing that 
- default data 
  - allows for quicker onboarding/data entry 
  - may cause inaccurate data
- no default data entry
  - slower onboarding/data 
  ## \- more likely accurate data
- Are null values possible?  If so, no default value is required.

**Comment by liamehinc** [comment]
LCCHP provided default values as outlined in the attached:
AddClient.aspx - All Yes/No questions should default to NULL and there should be an option to clear the selection
![image](https://cloud.githubusercontent.com/assets/1000622/7791725/3fc6bc70-0252-11e5-9d80-5b9948531b85.png)

EditClientIfno.aspx - All Yes/No questions should default to NULL and there should be an option to clear the selection
![image](https://cloud.githubusercontent.com/assets/1000622/7791730/56146b58-0252-11e5-9a70-098125f0ffc4.png)

**Comment by okkam1** [comment]
implemented per current spec from client; will modify in future if desired.
