### ISSUE TITLE
Updating family when more than 1 family has same property ID

### ISSUE THREAD

**Issue by liamehinc** [okkam1/BLT#235]
http://lakecounty.bloodlead.org:8080/EditFamily.aspx

if there are multiple families associated with the same address:

webpage doesn't appear to be passing @isNewAddress = 1, parameter in properly

```

Select FamilyID,LastName,PrimaryPropertyID,PropertyID,AddressLine1,AddressLine2 From Family AS F
JOIN Property AS P on F.PrimaryPropertyID = P.PropertyID
where PrimaryPropertyID in (    select PrimaryPropertyID from Family
                    GROUP by PrimaryPropertyID
                    having count(FamilyID) > 1)
```

if you add a new address All families associated with that address will have the address updated.

**Comment by okkam1** [comment]
done.  had to switch from internal members to session to cross a page post back barrier for the UI hiding certain fields.
