### ISSUE TITLE
UI - Need means of specifying person relationships

### ISSUE THREAD

**Issue by liamehinc** [okkam1/BLT#28]
The database has structure to support relationships between people. Will this functionality be added to the UI?

**Comment by okkam1** [comment]
what relationships does the customer want to specify?  For example the following reports are being requested: nursing mother's report and parent report.  These reports depend on a person relationship being defined.

**Comment by liamehinc** [comment]
Lynn is Reviewing this to determine if current implementation of client to family meets these requirements

**Comment by liamehinc** [comment]
duplicate of #101. 101 has more details, so i'm moving these notes to 101 and closing this ticket
