### ISSUE TITLE
UI - Dates show as datetime

### ISSUE THREAD

**Issue by liamehinc** [okkam1/BLT#30]
dates on the following reports are displaying as datetime (02/12/2014 12:00:00 AM) instead of date (02/12/2014). The database defines all these columns as date, can you update the code to be only date:

BirthDate in the following reports:
- List of New Clients (30, 60, 90)
- Full Report
- List of All Clients
- Clients by Blood Lead Level

The Clients by Blood Lead Level Report also has the following columns as datetime instead of date
- SampleDate
- Retest Bl
- Retest HB

**Comment by liamehinc** [comment]
all datetimes (mm/dd/yyyy hh:mm:sss) are displaying as dates (MM/dd/yyyy) only for the reports:

=CDate(Fields!BirthDate.Value).ToString("MM/dd/yyyy")

**Comment by spiet002** [comment]
Should "Created Date" for last 30, 60, 90 day reports still be displaying as datetime?
