### ISSUE TITLE
Reports - Search functionality

### ISSUE THREAD

**Issue by liamehinc** [okkam1/BLT#31]
•the search functionality is pretty poor. Amie can show us more detail, but I believe it's more related to searching for lead levels and the fact that the dates have times as well and have a bunch of 12s. Much of this will be alleviated by changing reports to only display date instead of datetime

**Comment by okkam1** [comment]
fixed (at least in part) by changing the datetime to date only.  this facilitates easier searching.

**Comment by spiet002** [comment]
Verified on 5/22/15
