### ISSUE TITLE
UI - Add New Client - date issues on client screen manifesting on questionnaire insert

### ISSUE THREAD

**Issue by liamehinc** [okkam1/BLT#33]
When I insert a birth date in a different format (01-15-15), it allows me to save the client and proceed to the next page. However, when I then try to save the next page, it pops up an error (Failed to convert parameter value from a String to a DateTime. So, I'm stuck on the next page, unable to fix my mistake on the previous page.

we were able to reproduce this during 2/24 demo with Cornelia and Lynn

**Comment by okkam1** [comment]
fixed by not passing date parameter to sproc if value is null

**Comment by spiet002** [comment]
Verified on 3/22/15
