### ISSUE TITLE
UI - New Family Screen - #'s are valid for the city name

### ISSUE THREAD

**Issue by liamehinc** [okkam1/BLT#35]
Able to add #s for city name

**Comment by okkam1** [comment]
we can add field validation to prevent this, but there are unusual names with numbers actually in the town name: for example, 29 Palms is an accepted spelling and so is "Hill Number 1"  http://en.wikipedia.org/wiki/Hill_Number_1,_Alabama

If anyone feels strongly about this, just re-open it and we'll add the validation.

**Comment by spiet002** [comment]
Verified on 3/22/15
