### ISSUE TITLE
UI - Blood Test Results - child status should be drop down

### ISSUE THREAD

**Issue by liamehinc** [okkam1/BLT#42]
child status should be a drop down list (data driven from the usp_SlChildStatus)

**Comment by okkam1** [comment]
Will, please fix the usp:

Msg 208, Level 16, State 1, Procedure usp_SlChildStatus, Line 20
Invalid object name 'Status'.

**Comment by okkam1** [comment]
ps i have the ui code done, please assign back to me.

**Comment by liamehinc** [comment]
the invalid objet name 'Status' error has been resolved

call the procedure as follows:
EXEC usp_SlChildStatus

**Comment by okkam1** [comment]
done: 

http://54.69.86.226:8080/bloodtestresults.aspx
