### ISSUE TITLE
UI - Don't allow future dates as input

### ISSUE THREAD

**Issue by liamehinc** [okkam1/BLT#43]
For any space that a date is input, I can choose a date that hasn't yet happened on the calendar. This could cause problems if someone scrolls ahead to the wrong calendar year.

**Comment by liamehinc** [comment]
I have made updates to the date fields in the database and restricted most of them to only allow dates that occur in the past as well as today.  I will get a list of the dates with restrictions in the database

**Comment by okkam1** [comment]
implemented on all dates in the on-boarding process.

**Comment by spiet002** [comment]
Verified on 3/22/15
