### ISSUE TITLE
Reports - new client doesn't show up in last 30 days report

### ISSUE THREAD

**Issue by liamehinc** [okkam1/BLT#48]
When I add a client and then go to the reports: They show up in last 30 days but not in Full Report. When I search for them, nothing comes up.

**Comment by liamehinc** [comment]
I checked the db and am able to pass both Date Last Painted: and Date of Last Remodel: NULL values without issue. 

It seems the issue is in the UI/web code

**Comment by liamehinc** [comment]
Resolved.

**Comment by spiet002** [comment]
Verified on 3/22/15
