### ISSUE TITLE
UI - Add Screens allow future dates

### ISSUE THREAD

**Issue by liamehinc** [okkam1/BLT#50]
Add new Client
- BirthDate (fixed by adding constraints):
  alter Table Person WITH CHECK ADD CONSTRAINT ck_Person_BirthDate CHECK ( (dbo.udf_DateInThePast([BirthDate]) = 1)  
  - MovedDate (fixed by adding constraint)
    alter Table Person WITH CHECK ADD CONSTRAINT ck_Person_MovedDate CHECK ( (dbo.udf_DateInThePast([MovedDate]) = 1) OR  MovedDate IS NULL)

BloodTestResults
- Sample Date
- QuestionnaireDate
- RemodelPropertyDate
- PaintDate

**Comment by liamehinc** [comment]
added constraints for the following, mandating the dates entered are not in the future:
NameofConstraint        TableName   ConstraintType
ck_RemediationActionPlan_RemediationActionPlanApprovalDate      RemediationActionPlan   CHECK_CONSTRAINT
ck_Remediation_RemediationApprovalDate      Remediation CHECK_CONSTRAINT
ck_Questionnaire_RemodelPropertyDate        Questionnaire   CHECK_CONSTRAINT
ck_Questionnaire_QuestionnaireDate      Questionnaire   CHECK_CONSTRAINT
ck_Questionnaire_PaintDate      Questionnaire   CHECK_CONSTRAINT
ck_PropertySampleResults_LabSubmissionDate      PropertySampleResults   CHECK_CONSTRAINT
CK_PositiveRange        DateRanges  CHECK_CONSTRAINT
ck_Person_MovedDate     Person  CHECK_CONSTRAINT
ck_Person_BirthDate     Person  CHECK_CONSTRAINT
ck_MediumSampleResults_MediumSampleDate     MediumSampleResults CHECK_CONSTRAINT
ck_BloodTestResults_SampleDate      BloodTestResults    CHECK_CONSTRAINT

**Comment by spiet002** [comment]
Verified on 3/22/15
