### ISSUE TITLE
UI - Questionnaire.aspx Date conversion error

### ISSUE THREAD

**Issue by spiet002** [okkam1/BLT#51]
ERROR: Failed to convert parameter value from a String to a DateTime. 2/21/2015 12:59:42 PM 

Added new client. Accepted defaults, including dates, and clicked next.

**Comment by liamehinc** [comment]
I checked the db and am able to pass both Date Last Painted: and Date of Last Remodel: NULL values without issue.

It seems the issue is in the UI/web code

**Comment by okkam1** [comment]
fixed

**Comment by spiet002** [comment]
Verified on 3/22/15
