### ISSUE TITLE
Reports - Full report is not working

### ISSUE THREAD

**Issue by liamehinc** [okkam1/BLT#54]
An error has occurred during report processing.
Cannot create a data reader for dataset 'FullReportDataSet'.

**Comment by okkam1** [comment]
executing the stored procedure used by this report: [usp_SLInsertedData], just returns a numeric value (207) rather than the dataset that was previously being used to populate the report.

**Comment by okkam1** [comment]
decision: let's remove it because it was not asked for and will require a non-trivial amount of effort to fix.
