### ISSUE TITLE
Onboard Client for Lead Research Study - Duplicate clients

### ISSUE THREAD

**Issue by spiet002** [okkam1/BLT#61]
Flag potential duplicate clients before added if there exists a client with all of the following

```
                                                           i.      Same Last name

                                                         ii.      Same First name

                                                        iii.      Same Date of Birth
```

**Comment by liamehinc** [comment]
I updated the usp_InsertPerson stored procedure to return an error if a row exists with the same FirstName, LastName, and BirthDate as the new entry from the usp_InsertNewCLientWebScreen
