### ISSUE TITLE
Questionnaire Web Screen - house built date

### ISSUE THREAD

**Issue by spiet002** [okkam1/BLT#66]
Add date house was built.

**Comment by okkam1** [comment]
for home visit questionnaire

**Comment by okkam1** [comment]
no parameter in questionnaire sproc for house build date.  Does this replace remodel date?

**Comment by okkam1** [comment]
does not replace remodel date.

**Comment by liamehinc** [comment]
The ups_InsertNewFamilyWebScreen accepts an input parameter Year_Build which is assigned to the property.  

Need to add another field to the AddFamily.aspx web screen for year built

**Comment by liamehinc** [comment]
Based on 20150325 LCCHP meeting: only concerned if pre 1978 or post 1978 - use checkbox/radiobutton

**Comment by liamehinc** [comment]
@okkam1  database supports adding year built as a 4 digit year (will show as jan 1 xxxx). Let's proceed with this and adjust in reports as necesssary

**Comment by liamehinc** [comment]
This was completed on the http://54.69.86.226:8080/AddFamily.aspx screen, now it needs to be added to the http://54.69.86.226:8080/EditFamily.aspx

**Comment by okkam1** [comment]
addressed by fix for #94
