### ISSUE TITLE
Questionnaire Web Screen - is home owned?

### ISSUE THREAD

**Issue by spiet002** [okkam1/BLT#67]
Radio Box for Home is owned (yes/no)

```
                                                           i.      Add homeowner field for rented homes

                                                         ii.      Include homeowner address and phone number
```

**Comment by liamehinc** [comment]
the database structure is in place to determine this. The property table has an ownerID and isOwnerOccupied field. 
We need to discuss how to integrate this with the web site

**Comment by okkam1** [comment]
the stored procedure does not take an input for home is owned.

**Comment by okkam1** [comment]
need to discuss which screen is appropriate for this field.  AddFamily with Property?  Do we need to identify a specific owner?

**Comment by liamehinc** [comment]
the parameter is @is_owner_Occuppied for the usp_InsertNewFamilyWebScreen stored procedure

**Comment by okkam1** [comment]
handled by previous issue #106
