### ISSUE TITLE
Questionnaire Web Screen - error entering data

### ISSUE THREAD

**Issue by spiet002** [okkam1/BLT#70]
Could not enter questionnaire data.

**Comment by liamehinc** [comment]
http://54.69.86.226:8080/Questionnaire.aspx

cannot pass blank string to any date fields on questionnaire page. It seems to be something with the way the Questionnaire.cs or Questionnaire.aspx is handling/formatting a blank string.

I can pass both a blank string and a null value in directly to the stored procedure call (usp_InsertNewQuestionnaireWebScreen).

**Comment by okkam1** [comment]
fixed by checking for blank dates and not passing parameter to sproc if date is blank

**Comment by spiet002** [comment]
Verified on 3/22/15
