### ISSUE TITLE
Help Icon for each Field

### ISSUE THREAD

**Issue by okkam1** [okkam1/BLT#72]
We would like to have help text for each field on the UI to help explain to the user what they should be entering.  We have asked Cornelia to provide a one sentence description of each field for this purpose.

**Comment by liamehinc** [comment]
a)  Onboard Client for Lead Research Study web screen
i)  Birth date – date the client was born
ii) Language – primary language spoken by the [family]
iii)    Ethnicity – childs’ ethnic background [dropdown: Spanish, English, other]
iv) Out of Site – Does the client live out of Lake County?
v)  Child Notes
b)  Lead Research Subject Questionnaire
i)  Questionnaire Date – Date the questionnaire was completed
ii) Paint: [Drop down Peeling, Flaking, Cracking in home]
iii)    Date last painted - date the home was last painted
iv) Remodeled  yes/no– When was residence remodeled
v)  Vitamins - does the client take vitamins with iron
vi) Hand Wash - does the client wash their hands regularly (3 - 4 or more times a day)
vii)    Bottle - does the client drink from a bottle
viii)   Breastfeading – Yes No Yes if the client is a mother nursing her child
ix) Pacifier - does the client use a pacifier
x)  Daycare notes
c)  Blood Lead Test Results
i)  Sample Date – date the lead and hemoglobin samples where obtained
ii)     Lab Date - date the results were received from the Lab
iii)    Blood Lead result (Pb) – lead value from the sample
iiv)    Flag – for follow up dates, (i.e. 30, 60 90 days, 6 mos.)
v)  Test type – how was the sample taken (venous or capillary draw)
vi) Lab – name of the lab the sample was processed by or source the sample results was obtained from dropdown LeadCare II, Tamarac, Other (fill in)
vii)    Child Status Code – what is the current status of the client Drop down Recheck, Closed, Moved, Resolved, Home Visit, Complete
viii)   Hemoglobin – Hemoglobin value from the sample

there are still several fields that need more clarification

**Comment by okkam1** [comment]
completed for Add.  Need to complete for update/edit sections.

**Comment by okkam1** [comment]
done for edit information
