### ISSUE TITLE
Add a New Family Page --Exception Caught

### ISSUE THREAD

**Issue by liamehinc** [okkam1/BLT#75]
http://54.69.86.226:8080/AddFamily.aspx
After entering in information, the following error was displayed after clicking "insert new family":

ERROR: Exception caught in AddFamily 3/9/2015 5:31:05 PM 

![leadville error](https://cloud.githubusercontent.com/assets/1000622/6566725/4e23467e-c672-11e4-9adb-f4cebdb1ccaf.jpg)

**Comment by okkam1** [comment]
AddFamily is now working correctly.

**Comment by spiet002** [comment]
Verified on 3/22/15
