### ISSUE TITLE
add family needs logic to not allow potential duplicates

### ISSUE THREAD

**Issue by okkam1** [okkam1/BLT#78]

**Comment by spiet002** [comment]
Not able to move on if "Potential Duplicates" warning appears.

**Comment by liamehinc** [comment]
stored procedure usp_InsertNewFamilyWebScreen accepts the following parameters:
@OverrideDuplicateProperty = 1,
@OverrideDuplicateFamilyPropertyAssociation = 1,

if they are 1, records will be inserted even if they appear to be duplicates
