### ISSUE TITLE
add Family Street number only accepts numbers

### ISSUE THREAD

**Issue by okkam1** [okkam1/BLT#82]
There are some  addresses with unusual numbers  528 1/2 or 345 2F, etc.  shouldn't the db should allow for those edge cases?

**Comment by okkam1** [comment]
Decision: merge three fields into one AddressLine1.  number, street, suffix

**Comment by liamehinc** [comment]
I've updated the database to merge streetnum, street, and street suffix into AddresLine1 and updated the InsertNewFmailyWebScreen (see below for template to use)

USE [LCCHPDev]
GO

DECLARE @return_value int,
        @FamilyID int

EXEC    @return_value = [dbo].[usp_InsertNewFamilyWebScreen]
        @FamilyLastName = N'Guevera',
        @Address_Line1 = N' 28 W. Glacier Hwy',
        @CityName = N'Juneau',
        @StateAbbr = N'AK',
        @ZipCode = N'99801',
        @Year_Built = '1945',
        @Owner_id = 4285,
        @is_Owner_Occupied = 1,
        @is_Residential = 1,
        @has_Peeling_Chipping_Paint = 0,
        @is_Rental = 0,
        @HomePhone = NULL,
        @WorkPhone = NULL,
        @Language = 3,
        @NumSmokers = 1,
        @Pets = 1,
        @inandout = 1,
        @FamilyNotes = N'''the love the mountains''',
        @PropertyNotes = N'some very nice remodling work',
        @DEBUG = 1,
        @FamilyID = @FamilyID OUTPUT

SELECT  @FamilyID as N'@FamilyID'

SELECT  'Return Value' = @return_value

GO

**Comment by okkam1** [comment]
closed b/c we are changing to accept address_Line1 as a varchar
