### ISSUE TITLE
Questionnaire Web Screen - make daycare a dropdown

### ISSUE THREAD

**Issue by spiet002** [okkam1/BLT#95]
Daycare should be dropdown:

i. Daycare

ii. Preschool

iii. Morning Star

iv. Head Start

v. Other

vi. None

**Comment by liamehinc** [comment]
liam to add the above to DB and provide query for Marco

**Comment by liamehinc** [comment]
EXEC usp_SLDaycare
OUTPUT looks like the following:
DaycareID   DaycareName DaycareDescription
1                   Daycare                  Child attends daycare
2                   Preschool                    Child attends preschool
3                   Moring Star Child attends Morning Star
4                   Head start                   Child attends Headstart
5                   Other                    Child attends some other form of childcare
6                   None                     Child does not attend any form of childcare

**Comment by liamehinc** [comment]
completed in dev, need to promote to public

**Comment by liamehinc** [comment]
pushed update to production
