### ISSUE TITLE
Blood Test Results Web Screen - child status code should be dropdown

### ISSUE THREAD

**Issue by spiet002** [okkam1/BLT#97]
make Child Status Code a dropdown:

i. Recheck

ii. Closed

iii. Moved

iv. Resolved

v. Home Visit

vi. Home Visit and Soil Sample

vii. Soil Sample

viii. Complete

**Comment by liamehinc** [comment]
liam to add the above to DB and provide query for Marco

**Comment by liamehinc** [comment]
stored procedure:
 usp_slChildStatus

OUTPUT:
Complete
Re-check
Closed
Moved
Resolved
Home Visit
Home Visit and Soil Sample
Soil Sample
