### ISSUE TITLE
Blood Test Results Web Screen - create dropdown for test type

### ISSUE THREAD

**Issue by spiet002** [okkam1/BLT#98]
Test Type should be a drop down (venous, capillary, both ) draws

**Comment by liamehinc** [comment]
database work is complete for this, the UI just needs to run the following stored procedure:

usp_slTargetSampleType 'person'

it returns sampleTypeID and SampleTypeName
SampleTypeID    SampleTypeName
8   Venous
9   Capillary
11  Both

**Comment by liamehinc** [comment]
liam to add the above to DB and provide query for Marco

**Comment by okkam1** [comment]
i guess this was moved?

Msg 2812, Level 16, State 62, Line 1
Could not find stored procedure 'usp_slTargetSampleType'.

**Comment by okkam1** [comment]
ps i have the ui code done, please assign back to me.

**Comment by liamehinc** [comment]
the stored procedure is there and works in LCCHPDev

![image](https://cloud.githubusercontent.com/assets/1000622/6721327/f54304ca-cd80-11e4-813d-a63d834d2402.png)

**Comment by liamehinc** [comment]
fixed issues by updating the code to make test type a drop down menu
